# ros_control_boilerplate Settings -----------------------
# Settings for ros_control control loop
generic_hw_control_loop:
  loop_hz: 30
  cycle_time_error_threshold: 0.04

# Settings for ros_control hardware interface
hardware_interface:
   sim_control_mode: 1 # 0: position, 1: velocity

FlexRay:
  serial: FTY4PDYV

  _SoftSpring: &SOFT
    constant: 0.0
    linear: 0.237536
    quadratic: -0.000032
    cubic: 0.0

  _MediumSpring: &MEDIUM
    constant: 0.0 #1.604382
    linear: 0.508932
    quadratic: -0.000117
    cubic: 0.0

  _HardSpring: &HARD
    constant: 1.186483
    linear: 0.938377
    quadratic: -0.000274
    cubic: 0.000001

  ganglion 0:
    muscle 0:
      id: left_biceps

      Force:
        output_pos_max: 1000
        output_neg_max: -1000
        time_period: 100.0
        rad_per_encoder_count: 0.00005788606746738269
        P_gain: 70
        I_gain: 0.0
        D_gain: 0
        forward_gain: 0.0
        dead_band: 0.0
        integral: 0.0
        integral_pos_min: 0.0
        integral_pos_max: 0.0
        sp_pos_min: -100.0
        sp_pos_max: 100.0
        torque: 1.0
        spring: *MEDIUM

      Velocity:
        output_pos_max: 1000
        output_neg_max: -1000
        time_period: 100.0
        rad_per_encoder_count: 0.00005788606746738269
        P_gain: 200.0
        I_gain: 0.0
        D_gain: 0.0
        forward_gain: 0.0
        dead_band: 0.0
        integral: 0.0
        integral_pos_min: 0.0
        integral_pos_max: 0.0
        sp_pos_min: -100.0
        sp_pos_max: 100.0

      Position:
        output_pos_max: 1000
        output_neg_max: -1000
        time_period: 100.0
        rad_per_encoder_count: 0.00005788606746738269
        P_gain: 100.0
        I_gain: 0.0
        D_gain: 0.0
        forward_gain: 0.0
        dead_band: 0.0
        integral: 0.0
        integral_pos_min: 0.0
        integral_pos_max: 0.0
        sp_pos_min: -100.0
        sp_pos_max: 100.0

    muscle 1:
      id: left_triceps

      Force:
        output_pos_max: 1000
        output_neg_max: -1000
        time_period: 100.0
        rad_per_encoder_count: 0.00005788606746738269
        P_gain: 70
        I_gain: 0.0
        D_gain: 0
        forward_gain: 0.0
        dead_band: 0.0
        integral: 0.0
        integral_pos_min: 0.0
        integral_pos_max: 0.0
        sp_pos_min: -100.0
        sp_pos_max: 100.0
        torque: 1.0
        spring: *MEDIUM

      Velocity:
        output_pos_max: 1000
        output_neg_max: -1000
        time_period: 100.0
        rad_per_encoder_count: 0.00005788606746738269
        P_gain: 200.0
        I_gain: 0.0
        D_gain: 0.0
        forward_gain: 0.0
        dead_band: 0.0
        integral: 0.0
        integral_pos_min: 0.0
        integral_pos_max: 0.0
        sp_pos_min: -100.0
        sp_pos_max: 100.0

      Position:
        output_pos_max: 1000
        output_neg_max: -1000
        time_period: 100.0
        rad_per_encoder_count: 0.00005788606746738269
        P_gain: 100.0
        I_gain: 0.0
        D_gain: 0.0
        forward_gain: 0.0
        dead_band: 0.0
        integral: 0.0
        integral_pos_min: 0.0
        integral_pos_max: 0.0
        sp_pos_min: -100.0
        sp_pos_max: 100.0

    muscle 2:
      id: left_supraspinatus

      Force:
        output_pos_max: 1000
        output_neg_max: -1000
        time_period: 100.0
        rad_per_encoder_count: 0.00005788606746738269
        P_gain: 70
        I_gain: 0.0
        D_gain: 0
        forward_gain: 0.0
        dead_band: 0.0
        integral: 0.0
        integral_pos_min: 0.0
        integral_pos_max: 0.0
        sp_pos_min: -100.0
        sp_pos_max: 100.0
        torque: 1.0
        spring: *MEDIUM

      Velocity:
        output_pos_max: 1000
        output_neg_max: -1000
        time_period: 100.0
        rad_per_encoder_count: 0.00005788606746738269
        P_gain: 200.0
        I_gain: 0.0
        D_gain: 0.0
        forward_gain: 0.0
        dead_band: 0.0
        integral: 0.0
        integral_pos_min: 0.0
        integral_pos_max: 0.0
        sp_pos_min: -100.0
        sp_pos_max: 100.0

      Position:
        output_pos_max: 1000
        output_neg_max: -1000
        time_period: 100.0
        rad_per_encoder_count: 0.00005788606746738269
        P_gain: 100.0
        I_gain: 0.0
        D_gain: 0.0
        forward_gain: 0.0
        dead_band: 0.0
        integral: 0.0
        integral_pos_min: 0.0
        integral_pos_max: 0.0
        sp_pos_min: -100.0
        sp_pos_max: 100.0

    muscle 3:
      id: left_pectoralis

      Force:
        output_pos_max: 1000
        output_neg_max: -1000
        time_period: 100.0
        rad_per_encoder_count: 0.00005788606746738269
        P_gain: 70
        I_gain: 0.0
        D_gain: 0
        forward_gain: 0.0
        dead_band: 0.0
        integral: 0.0
        integral_pos_min: 0.0
        integral_pos_max: 0.0
        sp_pos_min: -100.0
        sp_pos_max: 100.0
        torque: 1.0
        spring: *MEDIUM

      Velocity:
        output_pos_max: 1000
        output_neg_max: -1000
        time_period: 100.0
        rad_per_encoder_count: 0.00005788606746738269
        P_gain: 200.0
        I_gain: 0.0
        D_gain: 0.0
        forward_gain: 0.0
        dead_band: 0.0
        integral: 0.0
        integral_pos_min: 0.0
        integral_pos_max: 0.0
        sp_pos_min: -100.0
        sp_pos_max: 100.0

      Position:
        output_pos_max: 1000
        output_neg_max: -1000
        time_period: 100.0
        rad_per_encoder_count: 0.00005788606746738269
        P_gain: 100.0
        I_gain: 0.0
        D_gain: 0.0
        forward_gain: 0.0
        dead_band: 0.0
        integral: 0.0
        integral_pos_min: 0.0
        integral_pos_max: 0.0
        sp_pos_min: -100.0
        sp_pos_max: 100.0


# Publish all joint states ----------------------------------
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
   type:         joint_state_controller/JointStateController
   publish_rate: 50

# Joint Trajectory Controller -------------------------------
# For detailed explanations of parameter see http://wiki.ros.org/joint_trajectory_controller
effort_trajectory_controller:
   type: effort_controllers/JointTrajectoryController
   joints:
     - left_biceps
     - left_triceps
     - left_pectoralis
     - left_supraspinatus
   constraints:
      goal_time: 5.0
      #stopped_position_tolerance: 0.4 # Defaults to 0.01
      left_biceps:
          trajectory: 0.60
          goal:       0.15
      left_supraspinatus:
          trajectory: 0.60
          goal:       0.15
   # gains:
   #     joint1: {p: 2.0,  i: 0.0, d: 0.01, i_clamp: 1}
   #     joint2: {p: 2.0,  i: 0.0, d: 0.01, i_clamp: 1}

    # state_publish_rate:  50 # Defaults to 50
    # action_monitor_rate: 20 # Defaults to 20
    #hold_trajectory_duration: 0 # Defaults to 0.5rrrrr

# Individual Position Controllers ---------------------------------------
# Allows to send individual ROS msg of Float64 to each joint separately
joint1_position_controller:
   type: position_controllers/JointPositionController
   joint: muscle 0
   #pid: {p: 100.0, i: 0.01, d: 10.0}


# Group Position Controllers ---------------------------------------
# Allows to send single ROS msg of Float64MultiArray to all joints
joint_effort_controller:
   type: effort_controllers/JointGroupEffortController
   joints:
     - left_biceps
     - left_triceps
     - left_pectoralis
     - left_supraspinatus
